# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/redmi/begonia-ims/setup-makefiles.sh


PRODUCT_PACKAGES += \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
